// Auth
export const AUTH_SIGNUP_WITH_EMAIL = "AUTH_SIGNUP_WITH_EMAIL"
export const AUTH_CHANGE_STATUS     = "AUTH_CHANGE_STATUS"
export const SIGNUP_REQUESTED = "SIGNUP_REQUESTED"
export const SIGNUP_OK = "SIGNUP_RECEIVED"
export const SIGNUP_FAILED = "SIGNUP_FAILED"