// Auth
export const AUTH_SIGNUP_REQUESTED                          = "SIGNUP_REQUESTED"
export const AUTH_SIGNUP_OK                                 = "AUTH_SIGNUP_OK"
export const AUTH_SIGNUP_FAILED                             = "SIGNUP_FAILED"
export const AUTH_LOGIN_REQUESTED                           = "AUTH_LOGIN_REQUESTED"
export const AUTH_LOGIN_OK                                  = "AUTH_LOGIN_OK"
export const AUTH_LOGIN_FAILED                              = "AUTH_LOGIN_FAILED"
export const AUTH_VERIFICATION_REQUESTED                    = "AUTH_VERIFICATION_REQUESTED"
export const AUTH_VERIFICATION_OK                           = "AUTH_VERIFICATION_OK"
export const AUTH_VERIFICATION_FAILED                       = "AUTH_VERIFICATION_FAILED"

// STOCKS
export const STOCKS_COMPANY_REQUESTED                       = "STOCK_COMPANY_REQUESTED"
export const STOCKS_COMPANY_OK                              = "STOCK_COMPANY_OK"
export const STOCKS_COMPANY_FAILED                          = "STOCK_COMPANY_FAILED"
export const STOCKS_TRANSACTIONS_BY_COMPANY_REQUESTED       = "STOCKS_TRANSACTIONS_BY_COMPANY_REQUESTED"
export const STOCKS_TRANSACTIONS_BY_COMPANY_OK              = "STOCKS_TRANSACTIONS_BY_COMPANY_OK"
export const STOCKS_TRANSACTIONS_BY_COMPANY_FAILED          = "STOCKS_TRANSACTIONS_BY_COMPANY_FAILED"
export const STOCKS_TRANSACTIONS_BY_COMPANY_UPDATED_OK      = "STOCKS_TRANSACTIONS_BY_COMPANY_UPDATED_OK"
export const STOCKS_TRANSACTIONS_BY_USER_REQUESTED          = "STOCKS_TRANSACTIONS_BY_USER_REQUESTED"
export const STOCKS_TRANSACTIONS_BY_USER_OK                 = "STOCKS_TRANSACTIONS_BY_USER_OK"
export const STOCKS_TRANSACTIONS_BY_USER_FAILED             = "STOCKS_TRANSACTIONS_BY_USER_FAILED"

