// Auth
export const AUTH_SIGNUP_REQUESTED              = "SIGNUP_REQUESTED"
export const AUTH_SIGNUP_OK                     = "AUTH_SIGNUP_OK"
export const AUTH_SIGNUP_FAILED                 = "SIGNUP_FAILED"
export const AUTH_LOGIN_REQUESTED               = "AUTH_LOGIN_REQUESTED"
export const AUTH_LOGIN_OK                      = "AUTH_LOGIN_OK"
export const AUTH_LOGIN_FAILED                  = "AUTH_LOGIN_FAILED"
export const AUTH_VERIFICATION_REQUESTED        = "AUTH_VERIFICATION_REQUESTED"
export const AUTH_VERIFICATION_OK               = "AUTH_VERIFICATION_OK"
export const AUTH_VERIFICATION_FAILED           = "AUTH_VERIFICATION_FAILED"
